### ISSUE TITLE
执行下载打印过程失败

### ISSUE THREAD

**Issue by Counterrr** [DaYuMoon/electron-print-silent#3]
{
    "code": "500",
    "message": "执行下载打印过程失败: Operating System not supported"
}

**Comment by YuHuaOu** [comment]
1. 看一下调接口时的传参方式是否正确
2. 再看一下链接资源是否能正常访问

**Comment by YuHuaOu** [comment]
> { "code": "500", "message": "执行下载打印过程失败: Operating System not supported" }

1. 看一下调接口时的传参方式是否正确
2. 再看一下链接资源是否能正常访问

**Comment by Counterrr** [comment]
传参正确，资源也能正常访问

**Comment by YuHuaOu** [comment]
打印的文件是pdf格式的吗，还是图片？看错误提示是跟操作系统相关的，我这不知道怎么复现下这个问题

**Comment by Counterrr** [comment]
在线上http访问的pdf，我电脑是macOs m1

**Comment by YuHuaOu** [comment]
应该是没有适配mac平台的问题，我是基于win版本开发，应该是 pdf-to-printer 这个库打印pdf的时候抛的错误,，这个库只工作于windows，回头我看下做下兼容处理

**Comment by Counterrr** [comment]
https的pdf可以打印吗 看文档好像只支持http

**Comment by YuHuaOu** [comment]
支持的，只要资源能正常访问都能打印。如果你有windows的设备的话可以用windows平台试一下

**Comment by Counterrr** [comment]
windows下打印https的pdf报错
{
    "code": "500",
    "message": "执行下载打印过程失败: RequestError: certificate has expired"
}

**Comment by 80940279** [comment]
大神，怎么部署到服务器上？

**Comment by 80940279** [comment]
我是小白，怎么打包，怎么在电脑里安装打印应用




＂縩繼の簫＂
***@***.***







                       
Original Email
                       
                     

Sender:"YuHuaOu"< ***@***.*** &gt;;

Sent Time:2023/4/4 15:31

To:"YuHuaOu/electron-print"< ***@***.*** &gt;;

Cc recipient:"80940279"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;;

Subject:Re: [YuHuaOu/electron-print] 执行下载打印过程失败 (Issue #3)




  
大神，怎么部署到服务器上？
  
额，不是很明白你的意思，你是说怎么把这个服务部署到服务器上吗？
 这个是个桌面端的应用程序，直接在windows电脑上安装就好了，如果要用的话，直接下载安装包装到电脑上，前端直接调用接口就行了
 
&mdash;

**Comment by YuHuaOu** [comment]
> 我是小白，怎么打包，怎么在电脑里安装打印应用 ＂縩繼の簫＂ ***@***.*** Original Email Sender:"YuHuaOu"< ***@***.*** &gt;; Sent Time:2023/4/4 15:31 To:"YuHuaOu/electron-print"< ***@***.*** &gt;; Cc recipient:"80940279"< ***@***.*** &gt;;"Comment"< ***@***.*** &gt;; Subject:Re: [YuHuaOu/electron-print] 执行下载打印过程失败 (Issue #3) 大神，怎么部署到服务器上？ 额，不是很明白你的意思，你是说怎么把这个服务部署到服务器上吗？ 这个是个桌面端的应用程序，直接在windows电脑上安装就好了，如果要用的话，直接下载安装包装到电脑上，前端直接调用接口就行了 &mdash; Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

 使用windows平台的电脑，安装 Node.js 环境（要求为 node.js v14左右的版本），下载项目然后直接在项目根目录下打开shell，直接执行 yarn install 安装依赖，安装依赖完成后 执行 yarn build:win32 用于打包 windows平台的安装包

**Comment by Counterrr** [comment]
ok 我解决了 使用[unix-print](https://github.com/artiebits/unix-print) 来兼容mac的

**Comment by YuHuaOu** [comment]
> ok 我解决了 使用[unix-print](https://github.com/artiebits/unix-print) 来兼容mac的

没想到啊，竟然是一年后的回复了哈哈哈哈😂。
另外，这个库直接调用 print 方法就好了吗，是不是只能用于 macos 上的
